# remove local user account and groups

- name: remove obsolete local accounts and groups
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
    force: yes
  with_items: "{{ deluserlist  }}"
  ignore_errors: yes

