---
- name: roles to install initial RAM users,iptables etc 
  include_vars: 'main.yml'

# update all packages

- name: upgrade all packages
  yum: name=* state=latest

# install the repo for vmware tools version 6

- stat:
    path: /etc/yum.repos.d/vmware-osps.repo
  register: sym

- name: Install vmware repo verison 6 
  yum:
    name: "{{ item }}"
    state: present
    state: latest
    update_cache: yes
  with_items: 
       - http://packages.vmware.com/tools/esx/5.1/repos/vmware-tools-repo-RHEL6-9.0.0-2.x86_64.rpm
       - https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
  when: sym.stat.islnk is not defined and ansible_distribution_major_version == "6"

# Install required packages version 6


- name: Install python libraries and other packages
  yum:
    name: "{{ item }}"
    state: present
    state: latest
    update_cache: yes
  with_items:
         - libselinux-python
         - vmware-tools-esx
         - epel-release
         - nrpe
         - nagios-plugins-users
         - nagios-plugins-load
         - nagios-plugins-swap
         - nagios-plugins-disk
         - nagios-plugins-procs
         - net-snmp 
         - net-snmp-utils
         - rkhunter
         - aide
  when: ansible_distribution_major_version == "6"
  notify: Restart nrpe
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers


# Install required packages version 7

- name: Install epel_repo  for version 7
  yum:
    name: "{{ item }}"
    state: present
    state: latest
    update_cache: yes
  with_items:
         - epel-release
  when: ansible_distribution_major_version == "7"

- name: Install nrpe and other  packages for 7
  yum:
    name: "{{ item }}"
    state: present
    state: latest
    update_cache: yes
  with_items:
         - open-vm-tools
         - nrpe
         - nagios-plugins-users
         - nagios-plugins-load
         - nagios-plugins-swap
         - nagios-plugins-disk
         - nagios-plugins-procs
         - net-snmp 
         - net-snmp-utils
         - rkhunter
         - aide
  when: ansible_distribution_major_version == "7"
  notify: Restart nrpe
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers


- include: createusers.yml

- name:  Copy file resolv.conf
  copy: 
   src : resolv.conf
   dest: /etc/resolv.conf
   owner: root
   group: root
   mode : 0644
   backup: yes

- name:  Copy file rkhunter
  copy: 
   src : rkhunter.conf
   dest: /etc/rkhunter.conf
   owner: root
   group: root
   mode : 0644
   backup: yes

- name: Copy Template files snmpd
  template:
   src : "{{ item }}"
   dest: /etc/snmp/{{ item | basename | regex_replace('.j2','') }}
   owner: root
   group: root
   mode : 0644
   backup: yes
  with_items: 
    - snmpd.conf.j2

- name: Copy Template files main.cf 
  template:
   src : "{{ item }}"
   dest: /etc/postfix/{{ item | basename | regex_replace('.j2','') }}
   owner: root
   group: root
   mode : 0644
   backup: yes
  with_items: 
    - main.cf.j2

- name: Copy Template files iptables verison 6  - PLEASE RESTART IPTABLES MANUALLY ON SERVER (service iptables restart)
  template:
   src : "{{ item }}"
   dest: /etc/sysconfig/{{ item | basename | regex_replace('.6.j2','') }}
   owner: root
   group: root
   mode : 0644
   backup: yes
  with_items: 
   - iptables.6.j2
  when: (ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "6"

- name: Copy Template files iptables verison 7 - PLEASE RESTART IPTABLES MANUALLY ON SERVER (service iptables restart)
  template:
   src : "{{ item }}"
   dest: /etc/sysconfig/{{ item | basename | regex_replace('.7.j2','') }}
   owner: root
   group: root
   mode : 0644
   backup: yes
  with_items: 
   - iptables.7.j2
  when: (ansible_distribution == "OracleLinux" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "7"

#  notify: Restart iptables 
#- name: force all notified handlers to run at this point, not waiting for normal sync points
#  meta: flush_handlers

- lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: 'PermitRootLogin no'

- name: Check if aide db exists ...
  stat:
   path: /var/lib/aide/aide.db.gz
  register: aidestat 

- name: Create the initial aide database  
  shell: aide --init && mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
  when: aidestat.stat.islnk is not defined
